version: '3.8' 

services:
  postgresql:
    # pull the latest postgreSQL image
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: VERYSTRONGPASSWORD
      POSTGRES_DB: test_db
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgresql_init.sql:/docker-entrypoint-initdb.d/init.sql

  # DBeaver URL: jdbc:mysql://localhost:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: VERYSTRONGPASSWORD   
      MYSQL_DATABASE: test_db 
    ports:
      - 127.0.0.1:3306:3306 
    volumes:
      - ./mysql_init.sql:/docker-entrypoint-initdb.d/init.sql

