services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:5432:5432

  # DBeaver URL: jdbc:mysql://localhost:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 127.0.0.1:3306:3306 

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    restart: unless-stopped
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - 127.0.0.1:1433:1433
  
  oracle:
    image: container-registry.oracle.com/database/free:latest 
    restart: unless-stopped
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}
    ports:
      - 127.0.0.1:1521:1521

  app:
    build: .
    command: uvicorn web.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 127.0.0.1:80:8000
    depends_on:
      oracle:
        condition: service_healthy

